language: python
python:
    - "3.4"
    - "3.5"
sudo: required
install:
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage --cover-package ai --cover-min-percentage=90

notifications:
    email:
        cerebral.storming@gmail.com
